In [3]:
# create model class
import torch
import torch.nn as nn

h:\01_Training\ContentSlides_AgenticAI\Code\Pytorch\pt_env\Lib\site-packages\torch\_subclasses\functional_tensor.py:307: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\torch\csrc\utils\tensor_numpy.cpp:84.)
  cpu = _conversion_method_template(device=torch.device("cpu"))


In [ ]:


class Model(nn.Module):

  def __init__(self, num_features):
    super().__init__()
    self.network = nn.Sequential(
                                  nn.Linear(num_features, 3),
                                  nn.ReLU(),
                                  nn.Linear(3, 1),
                                  nn.Sigmoid()
                                )

  def forward(self, features):
    out = self.network(features)
    return out

In [ ]:
import torch
import torch.nn as nn

class Model(nn.Module):

  def __init__(self, num_features):
    super().__init__()
    self.linear1 = nn.Linear(num_features, 3)
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(3, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear1(features)
    out = self.relu(out)
    out =self.linear2(out) 
    out = self.sigmoid(out)
    return out


In [3]:
features = torch.rand(10,5)

In [4]:
print(features)

tensor([[0.7146, 0.8693, 0.3332, 0.4815, 0.7452],
        [0.5172, 0.2620, 0.1596, 0.4569, 0.2577],
        [0.8463, 0.2424, 0.0754, 0.8176, 0.9448],
        [0.0184, 0.5592, 0.9588, 0.5393, 0.0351],
        [0.5293, 0.5899, 0.9544, 0.5314, 0.0903],
        [0.9152, 0.0681, 0.9504, 0.2199, 0.9240],
        [0.3207, 0.9470, 0.5731, 0.2650, 0.1034],
        [0.0543, 0.8935, 0.6660, 0.5666, 0.5901],
        [0.8106, 0.1123, 0.1074, 0.3975, 0.4214],
        [0.7465, 0.2233, 0.8106, 0.5847, 0.5697]])


In [5]:
# create dataset


# create model
model = Model(features.shape[1])

# call model for forward pass
# model.forward(features)
model(features)

tensor([[0.4574],
        [0.4574],
        [0.4591],
        [0.4402],
        [0.4418],
        [0.4747],
        [0.4483],
        [0.4574],
        [0.4574],
        [0.4635]], grad_fn=<SigmoidBackward0>)

In [6]:
# show model weights
#model.linear2.weight
model.network[2].weight  # Accessing the second Linear layer's weight


Parameter containing:
tensor([[-0.4890,  0.0688,  0.1573]], requires_grad=True)

In [15]:
!pip install torchinfo

^C


  Using cached torchinfo-1.8.0-py3-none-any.whl.metadata (21 kB)
Using cached torchinfo-1.8.0-py3-none-any.whl (23 kB)



[notice] A new release of pip is available: 24.2 -> 25.0
[notice] To update, run: C:\Users\ASUS\AppData\Local\Programs\Python\Python312\python.exe -m pip install --upgrade pip


In [16]:
from torchinfo import summary

summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00